services:
  web:
    image: node:22
    container_name: frontend
    ports:
      - "5000:3000"
    working_dir: /app
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: yarn start
